# Generated by Django 4.2.2 on 2023-06-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='loan_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='name_borrowed',
        ),
        migrations.RemoveField(
            model_name='books',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='books',
            name='running_time',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_borrowed', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('running_time', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.books')),
            ],
        ),
    ]
