# Generated by Django 4.2.2 on 2023-06-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('book', '0005_remove_books_loan_date_remove_books_name_borrowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='name_borrowed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.user'),
            preserve_default=False,
        ),
    ]
