# Generated by Django 4.2.2 on 2023-06-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_loan_loan_date_alter_loan_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='running_time',
        ),
    ]
