# Generated by Django 4.2.2 on 2023-06-23 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_loan_evaluation_alter_book_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 15, 44, 0, 48364)),
        ),
    ]
