# Generated by Django 4.2.2 on 2023-06-23 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 15, 49, 56, 588975)),
        ),
    ]
