# Generated by Django 4.2.2 on 2023-06-27 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_loan_loan_date_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 10, 57, 57, 488225)),
        ),
    ]
