# Generated by Django 4.2.2 on 2023-06-28 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_loan_book_alter_loan_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='book_cover'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 22, 46, 24, 636018)),
        ),
    ]
